### ISSUE TITLE
Linear Transform faster than 2018/153

### ISSUE THREAD

**Issue by haochenuw** [kimandrik/HEAANBOOT#7]
I ran (for 64 slots with param Set-I)

`    TestScheme::testBootstrap(15, 23, 29, 620, 6, 2);
`
and got 

> Start SubSum
> SubSum time = 4292.4 ms
> Start CoeffToSlot
> CoeffToSlot time = 19754.6 ms
>Start SlotToCoeff
>SlotToCoeff time = 15063 ms

This total time is shorter than the 82.8s reported in Table 2. I am curious about the possible reasons. Thanks!

**Comment by kimandrik** [comment]
Hello, 
In the implementation lately, we improved the method described in the paper. Number of coefficients of polynomial m(x) is N, but they are real, so instead of calculating two separate matrix multiplicaition we calculated a single matrix muliplication, and obtained coefficients of plaintext m(x) encrypted as 
(m_0 + i * m_N/2, m_1 + i * m_{N/2+1}, ..., m_{N/2-1} + i * m_{N-1}). The computation time decreased roughly by a factor of two.
