### ISSUE TITLE
Reference for FFTSpecial

### ISSUE THREAD

**Issue by haochenuw** [kimandrik/HEAANBOOT#8]
Is the functionality of FFTSpecial 
a \in RR[x]/(x^N+1) --> a[zeta], a[zeta^5], a[zeta^25], ... ? 

Is there a referenece (e.g. paper) that proves the correctness of the  functionality of FFTSpecial?

**Comment by kimandrik** [comment]
Hello
May be you can find some discussions in https://eprint.iacr.org/2011/535.pdf Appendix C2

**Comment by haochenuw** [comment]
Thanks for the pointer. However it does not solve the question though. It decomposes the DFT_m matrix, but I think the FFTSpecial function decomposes the CRT_m somehow.

**Comment by kimandrik** [comment]
Yeah, you right, we found the formulas by ourselves and checked them in code. 
For FFTSpecial you can permute rows, so that FFTSpecial becomes 
a \in RR[x]/(x^N+1) --> a[zeta^{4i+1}] for this map you can do similar to DFT odd-even splitting and find relations between FFTSpecial_{m} and FFTSpecial_{m/2}. This is how we found the algorithms for FFTSpecial and FFTSpecialInv.

**Comment by haochenuw** [comment]
Okay thanks a bunch!
